POST http://localhost:8080/events
cpntent-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MTcxMDY5NTUsInVzZXJJZCI6MH0.Hwl4ScUR4UZAFRELxdAd_WgwfViBucvTI-vAJw4hi6U

{
  "name": "Test1 event",
  "description": "Another test event!!!",
  "location": "Another test location",
  "dateTime": "2026-01-01T15:30:00.000Z"
}