POST http://localhost:8080/events
cpntent-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE3MTAyNTQ2LCJ1c2VySWQiOjB9.eKIdlB7494d6a9cOMqx7CccpeJGrvxizpjjujSK4dPA

{
  "name": "Test1 event",
  "description": "Another test event!!!",
  "location": "Another test location",
  "dateTime": "2026-01-01T15:30:00.000Z"
}