POST http://localhost:8080/events
cpntent-type: application/json

{
  "name": "Test event 2",
  "description": "Another test event",
  "location": "Another test location",
  "dateTime": "2026-01-01T15:30:00.000Z"
}