DELETE http://localhost:8080/events/4
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE3MTAzNjExLCJ1c2VySWQiOjB9.On2lZ2jTQ16ppDNpLSVsqorrUKpEbaeFLGhhYi31XRI